version: "3.8"

services:
  nginx-manager:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    container_name: nginx-manager
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "83:81" # Admin Web Port
    environment:
      DB_MYSQL_HOST: "nginx-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - nginx-db
    networks:
      - avengers
      - nginx
  nginx-db:
    image: "jc21/mariadb-aria:latest"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - ./mariadb/data/mysql:/var/lib/mysql
    networks:
      - avengers
      - nginx
  nginx:
    image: nginx
    restart: always
    networks:
      - avengers
      - nginx

networks:
  avengers:
    driver: bridge
  nginx:
    driver: bridge