version: '3'

services:
  ironman:
    build:
      context: ./express-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - APP_NAME=Ironman
      - RABBITMQ_URI=amqp://brian:123456@rabbitmq:5672
    networks:
      - avengers

  captain-america:
    build:
      context: ./express-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - APP_NAME=Captain América
      - RABBITMQ_URI=amqp://brian:123456@rabbitmq:5672
    networks:
      - avengers

  thor:
    container_name: thor
    build:
      context: ./express-api
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - APP_NAME=Thor
      - RABBITMQ_URI=amqp://brian:123456@rabbitmq:5672
    networks:
      - avengers

  hulk:
    build:
      context: ./react-front
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - VITE_APP_PORT=3003
      - VITE_APP_NAME=Hulk
      - VITE_API_URL=http://127.0.0.1:3000/whoareyou
      - VITE_SOCKETIO_URL=http://127.0.0.1:3000
    networks:
      - avengers

  dr-strange:
    build:
      context: ./react-front
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - VITE_APP_PORT=3004
      - VITE_APP_NAME=Dr. Strange
      - VITE_API_URL=http://127.0.0.1:3002/whoareyou
      - VITE_SOCKETIO_URL=http://127.0.0.1:3000
    networks:
      - avengers

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./data/:/var/lib/rabbitmq/
        - ./log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: brian
        RABBITMQ_DEFAULT_PASS: 123456
    networks:
      - avengers

networks:
  avengers:
    driver: bridge